### ISSUE TITLE
socket.d Error: variable `core.stdc.errno.EWOULDBLOCK`  conflicts with enum 

### ISSUE THREAD

**Issue by BoQsc** [shove70/database#3]
These are initial errors when I tried using your database dub package on the latest dmd compiler.

```
C:\Users\boqsc\Desktop\database\database_postgresql>dub run
Fetching database 1.1.27 (getting selected version)...
Performing "debug" build using C:\Program Files\LDC 1.28\bin\ldc2.exe for x86_64.
database:postgresql 1.1.27: building configuration "library"...
C:\Users\boqsc\AppData\Local\dub\packages\database-1.1.27\database\postgresql\database\postgresql\socket.d(56,72): Error: variable `core.stdc.errno.EWOULDBLOCK` at C:\Program Files\LDC 1.28\bin\..\import\core\stdc\errno.d(251,10) conflicts with enum member `core.sys.windows.winsock2.EWOULDBLOCK` at C:\Program Files\LDC 1.28\bin\..\import\core\sys\windows\winsock2.d(181,5)
C:\Users\boqsc\AppData\Local\dub\packages\database-1.1.27\database\postgresql\database\postgresql\socket.d(85,72): Error: variable `core.stdc.errno.EWOULDBLOCK` at C:\Program Files\LDC 1.28\bin\..\import\core\stdc\errno.d(251,10) conflicts with enum member `core.sys.windows.winsock2.EWOULDBLOCK` at C:\Program Files\LDC 1.28\bin\..\import\core\sys\windows\winsock2.d(181,5)
C:\Program Files\LDC 1.28\bin\ldc2.exe failed with exit code 1.
```

This is my setup on Windows operating system:
## .\database_project.cmd 
```
@ECHO OFF

IF NOT EXIST ".\database_postgresql\" (
	mkdir ".\database_postgresql\"
	cd ".\database_postgresql\"
	dub init --non-interactive
	dub add database:postgresql
	cmd.exe
)
```
